### PR TITLE
fix: Add privacy manifest 

### PR DESCRIPTION
**Pull request by keelerm84**

### CODE REVIEW

**Review by tanderson-ld — APPROVED** [review]

**Comment by choulepoka** [comment]
Is there a way to stop the _tracking_ of users? Because tracking is a big deal in the Apple world, if the LD sdk tracks, when we have to request user's permission, and if the user says no, we gotta _stop_ tracking.

Is there a way to do that without crippling the LD integration? @keelerm84

**Comment by keelerm84** [comment]
> Is there a way to stop the _tracking_ of users? Because tracking is a big deal in the Apple world, if the LD sdk tracks, when we have to request user's permission, and if the user says no, we gotta _stop_ tracking.
> 
> Is there a way to do that without crippling the LD integration? @keelerm84

My apologies for the delay in getting back to your question!

It is my understanding that the type of data our SDK uses does not require user interaction for approval. We are not tracking users for advertisement purposes; rather, any identifier is consumer provided and sent to our servers for the purpose of flag evaluation and experimentation.

**Comment by choulepoka** [comment]
@keelerm84 If that is truly the case, then the following values should be `false`:
- `NSPrivacyTracking` 
- `NSPrivacyCollectedDataTypeTracking`

Otherwise, you are basically declaring to Apple that the LaunchDarkly Framework is tracking for the purpose of App Tracking Transparency.

**Comment by keelerm84** [comment]
@choulepoka Yes, you are correct. We had the type tracking field set incorrectly. This is being adjusted in https://github.com/launchdarkly/ios-client-sdk/pull/366 and should be out in the next patch release (9.6.2).

**Pull request merged**
