### PR TITLE
Resolve bugs in the iOS client

### PR DESCRIPTION
**Pull request by atlassian-gaustin**
This brings the iOS client up to full feature parity

### CODE REVIEW

**Comment by arun251** [comment]
Hi @atlassian-gaustin thanks for the PR! Do you mind describing the motivations behind these commits?

**Comment by atlassian-gaustin** [comment]
The iOS client was badly broken — example: you can’t just typecast a string into a dictionary or array.

Also, the long-lived network connection would time out and close because the server wouldn’t have any changes to push.

**Comment by atlassian-gaustin** [comment]
Also, there is no reason to keep around sources retrieved via CocoaPods (or Carthage). Let CocoaPods or Carthage manage the sources.

**Comment by atlassian-gaustin** [comment]
Incorporate necessary changes into roll-up PR.

**Pull request closed without merging**
