### PR TITLE
Roll-up PR that provides bug fixes for array and dictionary, as well as notification of server connection failure.

### PR DESCRIPTION
**Pull request by atlassian-gaustin**

### CODE REVIEW

**Comment by atlassian-gaustin** [comment]
This is the minimal changes to the SDK, including fixes for processing array and dictionary ("JSON content"), and notification if the server connection failed (in case the client is waiting).

**Comment by atlassian-gaustin** [comment]
Updated PR to resolve conflicts with the 2.5.1 release on master.

**Comment by atlassian-gaustin** [comment]
Is this ever going to get reviewed?

**Comment by RCacheaux** [comment]
Hi @arun251, I work with @atlassian-gaustin at Atlassian and we are working on integrating LD into our apps. We've currently forked the library and we are brining the fork into our products. This isn't super ideal because having the fork makes it difficult for us to uptake any fixes/updates pushed to the official SDK. Just wanted to check-in on this PR and get some advice as to whether we could contribute to the official SDK or if our best bet is to maintain the fork. Thanks so much.

**Comment by arun251** [comment]
Hi @atlassian-gaustin and @RCacheaux , I apologize for the delay. We took your PR and reworked it a bit in a private branch. We were holding out for another new feature to include in that release, but it turns out it's not ready yet for public consumption. We will release a 2.6.0 by EOD tomorrow with these fixes. Thanks again for the PRs!

**Comment by RCacheaux** [comment]
@arun251  Awesome that's great news, thanks for the update!

**Comment by arun251** [comment]
Thanks again for your fixes and improvements! We've incorporated them in the 2.6.0 release as part of a separate PR and given you credit for them. I'm closing this PR.

**Pull request closed without merging**
