### PR TITLE
Update Package.swift swift-tools-version 5.2

### PR DESCRIPTION
**Pull request by escakot**
**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [x] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [x] I have validated my changes against all supported platform versions (Using the build commands in config.yml)

**Related issues**
https://github.com/launchdarkly/ios-client-sdk/issues/233

**Describe the solution you've provided**
I've updated swift-tools-version to 5.2

**Describe alternatives you've considered**
N/A

**Additional context**
No updates required for `swift-eventsource` since it doesn't have dependencies.

### CODE REVIEW

**Comment by bwoskow-ld** [comment]
Hi @escakot,

Thank you for submitting a pull request to fix #233! At first glance the changes look reasonable. As @gwhelanLD mentioned [a few days ago](https://github.com/launchdarkly/ios-client-sdk/issues/233#issuecomment-757028008), we'll do some verification on our side and will get back to you.

Thanks,
@bwoskow-ld 

_Filed internally as 98439._

**Comment by escakot** [comment]
Hi @bwoskow-ld,

For sure. Appreciate you guys for taking the time to test it out. 

Thanks,
@escakot

**Comment by kreeger** [comment]
Hey, what's the status on this? If it's been forgotten, I'd like to give it a friendly bump. If it helps, I've got an updated copy of this change, but sitting on top the latest of the `v5` branch, in [our fork of this project](https://github.com/oreillymedia/ios-client-sdk/commit/15af06d4fb4647906acc65617906bf68d2be4a04).

**Comment by bwoskow-ld** [comment]
Hi @kreeger ,

This issue hasn't been forgotten, but thanks for the friendly bump. Apologies for not getting to it yet.

**Review by gwhelanLD — APPROVED** [review]

**Comment by gwhelanLD** [comment]
Thanks for the contribution! It's been included in the [5.4.2 release](https://github.com/launchdarkly/ios-client-sdk/releases/tag/5.4.2).

Thanks,
@gwhelanLD

**Pull request merged**
